
name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url}}
    steps:
    - id: deploy
      name: Deploy
      with:
        aws_access_key_id: ${{ secret.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secret:AWS_SECRET_ACCESS_KEY}}
        aws_default_region: us-east-1

        app_port: 3000